services:

  postgres:
    image: postgres:15
    container_name: postgres_nogtech

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: nogtech

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.9.1
    container_name: airflow_nogtech

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/nogtech

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./cache:/opt/airflow/cache

    command: bash -c "airflow standalone"

volumes:
  postgres_data: